### ISSUE TITLE
Recipe app project

### ISSUE THREAD

**Issue by huzaifakhan0308** [huzaifakhan0308/Recipe-app#12]
### Hey There:

You can go through our project with this link:

https://github.com/users/huzaifakhan0308/projects/2

we are Two team members in this project

- [Huzaifa khan](https://github.com/huzaifakhan0308)
- [Abdimulhin](https://github.com/AbdimulhinYussuf3675)

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @huzaifakhan0308 and @AbdimulhinYussuf3675,

✔️ Tasks are complete and well assigned

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AbdimulhinYussuf3675** [comment]
Thanks @TedLivist for approval
